# Generated by Django 3.2.7 on 2021-09-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LapApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopModel',
            new_name='Laptop',
        ),
    ]
